name: 'Package an artifact directory'
description: 'Packages an artifact directory'

inputs:
  action:
    required: true
    description: ''
  source:
    required: true
    description: ''
  target:
    required: true
    description: ''
runs:
  using: composite
  steps:
    - name: Compress source
      if: ${{ inputs.action == 'compress' }}
      shell: bash
      run: |
        cd ${{ inputs.source }}
        tar -zcvf ../${{ target }} .

    - name: Compress source
      if: ${{ inputs.action == 'extract' }}
      shell: bash
      run: |
        mkdir -p ${{ inputs.target }}
        tar -zxvf ${{ inputs.source }} -C ${{ inputs.target }}
