name: space control panel - UI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  API_URL_PRODUCTION: https://api.ufostart.com
  APP_URL_PRODUCTION: https://space-control-center.ufostart.com
  API_URL_STAGING: https://staging.api.ufostart.com
  APP_URL_STAGING: https://staging.space-control-center.ufostart.com

jobs:
  pre_merge_check:
    name: Pre merge check
    runs-on: ubuntu-latest
    steps:
      - name: Prepare variables
        id: environment_variables
        run: |
          echo "VITE_API_URL=${{ env.API_URL_STAGING }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2

      - name: Define node version
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.2'

      - name: debug variables
        run: |
          echo "event_name:     '${{github.event_name}}"
          echo "api url:        '${{ env.API_URL_STAGING }}'-env'${{ env.VITE_API_URL }}'-$VITE_API_URL"
          echo "app url:        '${{ env.APP_URL_STAGING }}'"
          echo "GITHUB_RUN_ID:  '$GITHUB_RUN_ID'"
          echo "GITHUB_SHA:     '$GITHUB_SHA'"

      # step one
      - name: Build, Test
        run: |
          echo "build & test for : VITE_API_URL='${{ env.VITE_API_URL }}'"
          sleep 10
          
          echo 'yarn install'
          echo 'yarn code:style'
          echo 'yarn code:analyse'
          echo 'yarn build'
          echo 'yarn test'
          
          ./shell_script.sh
          if [[ ! -d dist ]]; then
            mkdir -p dist
          fi
          echo "VITE_API_URL: '${VITE_API_URL}'" > dist/artifact.txt
        env:
          SHELL_SCRIPT_RESULT_OK: ${{ secrets.SHELL_SCRIPT_RESULT_OK }}

      # when push instead of merge
      - name: Upload UI build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ui_artifact_pre_merge_check
          path: dist/
          retention-days: 30

  build_and_deploy_staging:
    name: Build & Deploy to staging
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [pre_merge_check]
    environment:
      name: staging
      url: ${{ steps.environment_variables.outputs.app_url }}
    steps:
      - name: Prepare variables
        id: environment_variables
        run: |
          echo "::set-output name=api_url::${{ env.API_URL_STAGING }}"
          echo "::set-output name=app_url::${{ env.APP_URL_STAGING }}"
          echo "VITE_API_URL=${{ env.API_URL_STAGING }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2

      - name: Define node version
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.2'

      - name: debug variables
        run: |
          echo "event_name:     '${{github.event_name}}"
          echo "api url:        '${{ env.API_URL_STAGING }}'-env'${{ env.VITE_API_URL }}'-$VITE_API_URL"
          echo "app url:        '${{ env.APP_URL_STAGING }}'"
          echo "GITHUB_RUN_ID:  '$GITHUB_RUN_ID'"
          echo "GITHUB_SHA:     '$GITHUB_SHA'"

      - name: Build, Test
        run: |
          echo "build & test for : VITE_API_URL='${{ env.VITE_API_URL }}'"
          sleep 10
          
          echo 'yarn install'
          echo 'yarn code:style'
          echo 'yarn code:analyse'
          echo 'yarn build'
          echo 'yarn test'
          
          ./shell_script.sh
          if [[ ! -d dist ]]; then
            mkdir -p dist
          fi
          echo "VITE_API_URL: '${VITE_API_URL}'" > dist/artifact.txt
        env:
          SHELL_SCRIPT_RESULT_OK: ${{ secrets.SHELL_SCRIPT_RESULT_OK }}

      - name: Upload UI build artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: ui_artifact_staging
          path: dist/
          retention-days: 30

      - name: Deploy artifact
        run: |
          cat dist/artifact.txt

  build_and_deploy_production:
    name: Build & Deploy to production
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [pre_merge_check,build_and_deploy_staging]
    environment:
      name: production
      url: ${{ steps.environment_variables.outputs.app_url }}
    steps:
      - name: Prepare variables
        id: environment_variables
        run: |
          echo "::set-output name=api_url::${{ env.API_URL_PRODUCTION }}"
          echo "::set-output name=app_url::${{ env.APP_URL_PRODUCTION }}"
          echo "VITE_API_URL=${{ env.API_URL_PRODUCTION }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2

      - name: Define node version
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.2'

      - name: debug variables
        run: |
          echo "event_name:     '${{github.event_name}}"
          echo "api url:        '${{ env.API_URL_STAGING }}'-env'${{ env.VITE_API_URL }}'-$VITE_API_URL"
          echo "app url:        '${{ env.APP_URL_STAGING }}'"
          echo "GITHUB_RUN_ID:  '$GITHUB_RUN_ID'"
          echo "GITHUB_SHA:     '$GITHUB_SHA'"

      - name: Build, Test
        run: |
          echo "build & test for : VITE_API_URL='${{ env.VITE_API_URL }}'"
          sleep 10
          
          echo 'yarn install'
          echo 'yarn code:style'
          echo 'yarn code:analyse'
          echo 'yarn build'
          echo 'yarn test'
          
          ./shell_script.sh
          if [[ ! -d dist ]]; then
            mkdir -p dist
          fi
          echo "VITE_API_URL: '${VITE_API_URL}'" > dist/artifact.txt
        env:
          SHELL_SCRIPT_RESULT_OK: ${{ secrets.SHELL_SCRIPT_RESULT_OK }}

      - name: Upload UI build artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: ui_artifact_production
          path: dist/
          retention-days: 30

      - name: Deploy artifact
        run: |
          cat dist/artifact.txt
