# Action that is able to actually release an artifact to an environment
name: Build & Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, production ]

  pull_request:
    branches: [ main, production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  check_build_test:
    name: Check, build & test artifact
    runs-on: ubuntu-latest
    env:
      # 👇 is directly connected with production branch
      API_URL_PRODUCTION: https://ApiUrlProduction
      # 👇 is directly connected with main
      API_URL_STAGING: https://ApiUrlStaging
      VITE_API_URL: ''

    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.2'

      - name: Resolve api url for environment
        run: |
          resolves_url=''
          
          if [[ ${{ steps.branch-name.outputs.current_branch }} == 'main' ]]; then
            resolves_url='${{ env.API_URL_STAGING }}'
          fi

          if [[ ${{ steps.branch-name.outputs.current_branch }} == 'production' ]]; then
            resolves_url='${{ env.API_URL_PRODUCTION }}'
          fi
          
          echo "VITE_API_URL=${resolves_url}" >> $GITHUB_ENV

      - name: github event_name ?
        run: |
          echo 'event_name ${{github.event_name}}'

      # step one
      # @todo yarn install
      # @todo yarn code:style
      # @todo yarn code:analyse
      # @todo yarn build
      - name: Build, Test
        run: |
          echo "build & test for : VITE_API_URL='${{ env.VITE_API_URL }}'"
          sleep 10
          ./shell_script.sh
          if [[ ! -d dist ]]; then
            mkdir -p dist
          fi
          echo "VITE_API_URL: '${VITE_API_URL}'" > dist/artifact.txt
        env:
          SHELL_SCRIPT_RESULT_OK: ${{ secrets.SHELL_SCRIPT_RESULT_OK }}
      # @todo yarn test

      # when push instead of merge
      - name: Upload UI build artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
          retention-days: 30

      # @todo store artifact
      # @todo deploy artifact

  deployment:
    name: Deploy artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download UI build artifact
        if: github.event_name == 'push'
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Deploy artifact
        if: github.event_name == 'push'
        run: |
          cat dist/artifact.txt
