name: space control panel - UI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  ARTIFACT_NAME: 'ui artifact'
  ARTIFACT_RETENTION_DAYS: 30
  ARTIFACT_BUILD_TARGET_FILEPATH: './dist/'
  ARTIFACT_BUCKET_NAME: 'space-control-panel-artifacts'
  #  ARTIFACT_ACCESS_KEY_ID: @info needs to be defined in 'github > Settings > Secrets > Actions'
  #  ARTIFACT_SECRET_ACCESS_KEY: @info needs to be defined in 'github > Settings > Secrets > Actions'

  DEFAULT_API_URL_PLACEHOLDER_FILEPATH: ./dist/index.html
  DEFAULT_API_URL_PLACEHOLDER: '%%API_URL_PLACEHOLDER%%'

  NODE_VERSION: '14.18.2'

  API_URL_PRODUCTION: https://api.ufostart.com
  APP_URL_PRODUCTION: https://space-control-panel.ufostart.com
  TAG_NAME_PRODUCTION: production
  APP_S3_BUCKET_NAME_PRODUCTION: space-control-panel.ufostart.com
  #  APP_S3_ACCESS_KEY_ID_PRODUCTION: @info needs to be defined in 'github > Settings > Secrets > Actions'
  #  APP_S3_SECRET_ACCESS_KEY_PRODUCTION: @info needs to be defined in 'github > Settings > Secrets > Actions'

  API_URL_STAGING: https://staging.api.ufostart.com
  APP_URL_STAGING: https://staging-space-control-panel.ufostart.com
  TAG_NAME_STAGING: staging
  APP_S3_BUCKET_NAME_STAGING: staging-space-control-panel.ufostart.com
  #  APP_S3_ACCESS_KEY_ID_STAGING: @info needs to be defined in 'github > Settings > Secrets > Actions'
  #  APP_S3_SECRET_ACCESS_KEY_STAGING: @info needs to be defined in 'github > Settings > Secrets > Actions'

jobs:
  build_and_test:
    name: Build and test UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment values
        id: environment_values
        uses: ./.github/actions/define-environment-values
        with:
          api-url: ${{ env.API_URL_STAGING }}
          app-url: ${{ env.APP_URL_STAGING }}

      - name: Define node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: debug variables
        run: |
          echo "event_name:     '${{github.event_name}}"
          echo "api url:        '${{ steps.environment_values.outputs.api-url }}'"
          echo "app url:        '${{ steps.environment_values.outputs.app-url }}'"
          echo "GITHUB_RUN_ID:  '$GITHUB_RUN_ID'"
          echo "GITHUB_SHA:     '$GITHUB_SHA'"

      - name: Inspect filesystem
        run: |
          tree -a -L 2

      - name: Resolve issue number
        id: resolved_issue_number
        uses: ./.github/actions/resolve-issue-number

      - name: Resolve artifact
        id: resolved_artifact
        uses: ./.github/actions/resolve-artifact
        with:
          issue-number: ${{ steps.resolved_issue_number.outputs.issue-number }}
          sha: ${{ github.sha }}
          bucket-name: ${{ env.ARTIFACT_BUCKET_NAME }}

      - name: Build UI artifact
        uses: ./.github/actions/build-ui-artifact
        with:
          target-directory: ${{ env.ARTIFACT_BUILD_TARGET_FILEPATH }}

      - name: Create version file
        uses: ./.github/actions/create-version
        with:
          issue-number: ${{ steps.resolved_issue_number.outputs.issue-number }}
          sha: ${{ github.sha }}
          built-at: ${{ steps.environment_values.outputs.current-datetime }}

      - name: Inspect filesystem
        run: |
          ls -al ./dist
          tree -a -L 2

      - name: Compress artifact
        uses: ./.github/actions/package-artifact
        with:
          action: 'compress'
          source: ${{ env.ARTIFACT_BUILD_TARGET_FILEPATH }}
          target: '${{ steps.resolved_artifact.outputs.filename }}'

      - name: Publish artifact to S3 artifact store
        uses: ./.github/actions/aws-s3-artifact-transfer
        with:
          access-key-id: ${{ secrets.ARTIFACT_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.ARTIFACT_SECRET_ACCESS_KEY }}
          region: ${{ secrets.ARTIFACT_REGION }}
          source-path: './${{ steps.resolved_artifact.outputs.filename }}'
          target-path: '${{ steps.resolved_artifact.outputs.s3-url }}'
          transfer-directory: false

      - name: Create artifact comment
        id: create_artifact_comment
        uses: actions/github-script@v6
        with:
          script: |
            const { default: createCommentWithPayload } = await import('${{ github.workspace }}/.github/src/create-comment-with-payload.js')

            const issueMessage = [
              '**Artifact created** ${{ steps.resolved_artifact.outputs.filename }}',
              '                     ${{ steps.resolved_artifact.outputs.s3-url }}'
            ].join('\r\n')

            const issueData = {
                artifactUrl: '${{ steps.resolved_artifact.outputs.s3-url }}',
            }

            await createCommentWithPayload(
                {github, config: { owner: context.repo.owner, repo: context.repo.repo }},
                ${{ steps.resolved_issue_number.outputs.issue-number }},
                issueMessage,
                issueData,
            )


  deploy_to_staging:
    name: Deploy UI to staging
    runs-on: ubuntu-latest
    #if: github.event_name == 'push'
    needs: [build_and_test]
    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment values
        id: environment_values
        uses: ./.github/actions/define-environment-values
        with:
          api-url: ${{ env.API_URL_STAGING }}
          app-url: ${{ env.APP_URL_STAGING }}
          environment-name: staging

      - name: Resolve issue number
        id: resolved_issue_number
        uses: ./.github/actions/resolve-issue-number

      - name: Resolve current artifact url
        id: resolved_artifact_url
        uses: actions/github-script@v6
        with:
          script: |
            const { resolveLastCommentsData } = await import('${{ github.workspace }}/.github/src/resolve-last-comments-data.js')
            
            const resolvedLastCommentsData = await resolveLastCommentsData(
              {github, config: { owner: context.repo.owner, repo: context.repo.repo }},
              ${{ steps.resolved_issue_number.outputs.issue-number }}
            )
            
            return resolvedLastCommentsData?.artifactUrl ?? null

      - name: Fetch artifact to S3 artifact store
        uses: ./.github/actions/aws-s3-artifact-transfer
        with:
          access-key-id: ${{ secrets.ARTIFACT_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.ARTIFACT_SECRET_ACCESS_KEY }}
          region: ${{ secrets.ARTIFACT_REGION }}
          source-path: ${{ steps.resolved_artifact_url.outputs.result }}
          target-path: './${{ steps.resolved_artifact.outputs.filename }}'
          transfer-directory: false

      - name: Resolve artifact
        id: resolved_artifact
        uses: ./.github/actions/resolve-artifact
        with:
          issue-number: ${{ steps.resolved_issue_number.outputs.issue-number }}
          sha: ${{ github.sha }}
          bucket-name: ${{ env.ARTIFACT_BUCKET_NAME }}

      - name: Inspect filesystem
        run: |
          tree -a -L 2

      - name: Extract artifact
        uses: ./.github/actions/package-artifact
        with:
          action: 'extract'
          source: ./${{ steps.resolved_artifact.outputs.filename }}
          target: './dist'

      - name: Inspect filesystem
        run: |
          tree -a -L 2

      - name: Update version file
        uses: ./.github/actions/update-version
        with:
          environment-name: ${{ steps.environment_values.outputs.environment-name }}
          deployment-timestamp: ${{ steps.environment_values.outputs.current-datetime }}

      - name: Define api url
        uses: ./.github/actions/replace-string-in-file
        with:
          filepath: ${{ env.DEFAULT_API_URL_PLACEHOLDER_FILEPATH }}
          search: ${{ env.DEFAULT_API_URL_PLACEHOLDER }}
          replacement: ${{ steps.environment_values.outputs.api-url }}

      - name: Deploy artifact
        uses: ./.github/actions/aws-s3-artifact-transfer
        with:
          access-key-id: ${{ secrets.APP_S3_ACCESS_KEY_ID_STAGING }}
          secret-access-key: ${{ secrets.APP_S3_SECRET_ACCESS_KEY_STAGING }}
          region: ${{ secrets.ARTIFACT_REGION }}
          source-path: '${{ env.ARTIFACT_BUILD_TARGET_FILEPATH }}'
          target-path: s3://${{ env.APP_S3_BUCKET_NAME_STAGING }}
          transfer-directory: true

      - name: Check deployment
        uses: ./.github/actions/check-deployment
        with:
          app-url: ${{ env.APP_URL_STAGING }}

      # - name: Tag issue with failed deployment
      - name: Label issue on failure
        if: failure()
        run: |
          echo 'ERROR: I run only on failure'
          ls -al ./dist
          tree -a -L 3
          exit 1

      - name: Label issue on failure
        uses: actions/github-script@v6
        if: failure()
        with:
          result-encoding: string
          script: |
            const issue = await github.rest.issues.addLabels({
                owner: issueConfig.owner,
                repo: issueConfig.repo,
                issue_number: parseInt( issueConfig.issueNumber),
                labels: ['deployment:failed:${{ steps.environment_values.outputs.environment-name }}']
            })

      - name: Tag artifact
        uses: ./.github/actions/add-environment-datetime-tag
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          environment-name: ${{ env.TAG_NAME_STAGING }}
          datetime: ${{ steps.environment_values.outputs.current-datetime }}

#  deploy_to_production:
#    name: Deploy UI to production
#    runs-on: ubuntu-latest
#    # if: github.event_name == 'push'
#    needs: [build_and_test,deploy_to_staging]
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Prepare environment values
#        id: environment_values
#        uses: ./.github/actions/define-environment-values
#        with:
#          api-url: ${{ env.API_URL_PRODUCTION }}
#          app-url: ${{ env.APP_URL_PRODUCTION }}
#
#      - name: Fetch UI build artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: ${{ env.ARTIFACT_NAME }}
#          path: ${{ env.ARTIFACT_BUILD_TARGET_FILEPATH }}
#
#      - name: Define api url
#        uses: ./.github/actions/replace-string-in-file
#        with:
#          filepath: ${{ env.DEFAULT_API_URL_PLACEHOLDER_FILEPATH }}
#          search: ${{ env.DEFAULT_API_URL_PLACEHOLDER }}
#          replacement: ${{ steps.environment_values.outputs.api-url }}
#
#      - name: Deploy artifact
#        run: |
#          cat '${{ env.ARTIFACT_BUILD_TARGET_FILEPATH }}/artifact.txt'
#
#      - name: Tag artifact
#        uses: ./.github/actions/add-environment-datetime-tag
#        if: always()
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          environment-name: ${{ env.TAG_NAME_PRODUCTION }}
#          datetime: ${{ steps.environment_values.outputs.current-datetime }}
